// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-YqTzLQCvujyZWOMKTZFowIUXyhTEhQ',
    appId: '1:747860813477:web:6d830fe0c5a77f88cdcf4c',
    messagingSenderId: '747860813477',
    projectId: 'mindflow-66822',
    authDomain: 'mindflow-66822.firebaseapp.com',
    storageBucket: 'mindflow-66822.firebasestorage.app',
    measurementId: 'G-FR98XEJMHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3w1WXESfir1_nZ9TcRiHYf1ouY7S1X2w',
    appId: '1:747860813477:android:75942d36bc5bde1ecdcf4c',
    messagingSenderId: '747860813477',
    projectId: 'mindflow-66822',
    storageBucket: 'mindflow-66822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNt2dymxex_MGk_b48cH3PRlU1keKrBM',
    appId: '1:747860813477:ios:f5c69b50d5cb3eb2cdcf4c',
    messagingSenderId: '747860813477',
    projectId: 'mindflow-66822',
    storageBucket: 'mindflow-66822.firebasestorage.app',
    iosBundleId: 'com.example.mindflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJNt2dymxex_MGk_b48cH3PRlU1keKrBM',
    appId: '1:747860813477:ios:f5c69b50d5cb3eb2cdcf4c',
    messagingSenderId: '747860813477',
    projectId: 'mindflow-66822',
    storageBucket: 'mindflow-66822.firebasestorage.app',
    iosBundleId: 'com.example.mindflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn-YqTzLQCvujyZWOMKTZFowIUXyhTEhQ',
    appId: '1:747860813477:web:ed0aa7c08d3cdfa4cdcf4c',
    messagingSenderId: '747860813477',
    projectId: 'mindflow-66822',
    authDomain: 'mindflow-66822.firebaseapp.com',
    storageBucket: 'mindflow-66822.firebasestorage.app',
    measurementId: 'G-FMEF6C7L94',
  );
}
